#creating an artifacts folder
artifacts_root: "artifacts"

#I've already download the file so no need for all of these config parameters
data_ingestion:
  root_dir: "artifacts/data_ingestion"
  unzip_dir: "artifacts/data_ingestion"
  source_url: " "
  local_data_file: " "
  # local_data_file: "artifacts/data_ingestion/data.zip"



prepare_base_ML:
  root_dir: "artifacts/prepare_base_ML"
  base_model_path: "artifacts/prepare_base_ML/base_model.h5"
  updated_base_model_path: "artifacts/prepare_base_ML/updated_base_model.h5"


training_ML:
  root_dir: "artifacts/training_ML"
  trained_model_path: "artifacts/training_ML/model.h5"




